# fly.toml app configuration file generated for fp on 2024-11-21T13:58:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fp"
primary_region = "lhr"

[build]
  # dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[resources]
  memory = "1GB"
  cpu = "shared"
